version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE= db
      - MYSQL_ROOT_PASSWORD= adminpira*123
      - MYSQL_USER=admin
      - MYSQL_PASSWORD= pira*123
    ports:
      - '3306:3306'
    volumes:
      - mysql:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mysql:
    driver: local
